# for local development
services:
    frontend:
        build:
            context: .
            target: 'develop-stage'
        ports:
            - '9000:9000'
        volumes:
            - '.:/app'
        command: /bin/sh -c "yarn quasar dev"
